config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :meetups

  resources :companies

  resources :jobs

  root to: "meetups#index"
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/models/meetup.rb
class Meetup < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :logo_url, :url)
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :company_id, :description, :link)
    end
end

app/controllers/meetups_controller.rb
require 'rmeetup'

class MeetupsController < ApplicationController
  before_action :set_meetup, only: [:show, :edit, :update, :destroy]

  # GET /meetups
  # GET /meetups.json
  def index
    client = RMeetup::Client.new do |config|
      config.api_key = "****"
    end
    results = client.fetch(:events, { group_id: '3618542', status: 'upcoming' })

    @meetup = results.first

    @meetups = Meetup.all
  end

  # GET /meetups/1
  # GET /meetups/1.json
  def show
  end

  # GET /meetups/new
  def new
    @meetup = Meetup.new
  end

  # GET /meetups/1/edit
  def edit
  end

  # POST /meetups
  # POST /meetups.json
  def create
    @meetup = Meetup.new(meetup_params)

    respond_to do |format|
      if @meetup.save
        format.html { redirect_to @meetup, notice: 'Meetup was successfully created.' }
        format.json { render :show, status: :created, location: @meetup }
      else
        format.html { render :new }
        format.json { render json: @meetup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetups/1
  # PATCH/PUT /meetups/1.json
  def update
    respond_to do |format|
      if @meetup.update(meetup_params)
        format.html { redirect_to @meetup, notice: 'Meetup was successfully updated.' }
        format.json { render :show, status: :ok, location: @meetup }
      else
        format.html { render :edit }
        format.json { render json: @meetup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetups/1
  # DELETE /meetups/1.json
  def destroy
    @meetup.destroy
    respond_to do |format|
      format.html { redirect_to meetups_url, notice: 'Meetup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meetup
      @meetup = Meetup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meetup_params
      params.require(:meetup).permit(:title, :date, :address, :host_id, :description, :meetup_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/meetups_helper.rb
module MeetupsHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :logo_url %><br>
    <%= f.text_field :logo_url %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Logo url</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.logo_url %></td>
        <td><%= company.url %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Logo url:</strong>
  <%= @company.logo_url %>
</p>

<p>
  <strong>Url:</strong>
  <%= @company.url %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br>
    <%= f.number_field :company_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<h1>Listing jobs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Company</th>
      <th>Description</th>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.company_id %></td>
        <td><%= job.description %></td>
        <td><%= job.link %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>

<p>
  <strong>Company:</strong>
  <%= @job.company_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<p>
  <strong>Link:</strong>
  <%= @job.link %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <title>Amsterdam.rb</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <link href="http://fonts.googleapis.com/css?family=Leckerli+One" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Abel" rel="stylesheet" type="text/css">
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-3300381-18']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
  </head>

  <body>
   <%= render 'shared/header' %>
    <div class="wrap">
      <div id="main">
           <%= yield %>

          <%= render 'shared/supporters' %>
          </div>
      </div>
      <%= render 'shared/footer' %>
  </body>
</html>

app/views/meetups/_form.html.erb
<%= form_for(@meetup) do |f| %>
  <% if @meetup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meetup.errors.count, "error") %> prohibited this meetup from being saved:</h2>

      <ul>
      <% @meetup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :host_id %><br>
    <%= f.number_field :host_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :meetup_url %><br>
    <%= f.text_field :meetup_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meetups/_meetup.html.erb
<section id="meetup">
  <h1 class="tag">
    <span class="tagleft"></span>
    <span class="text">
      <span>Next Meet-Up</span>
    </span>
    <span class="tagright"></span>
  </h1>
  <div id="map">
    <div id="company">
      <h2><%= @meetup.name %></h2>
      <div class="date-loc">
        <p class="date"><%= @meetup.time.to_formatted_s(:long) %></p>
        <p class="loc"><%= @meetup.venue.name %> (<%= @meetup.venue.address_1 %>)</p>
      </div>
      <div class="content">
        <%= @meetup.description.html_safe %>
      </div>
      <a class="button" href="http://www.meetup.com/Amsterdam-rb/events/<%= @meetup.id %>/">Sign up at Meetup</a>
    </div>
    <div class="mapbox"><a href="http://maps.google.nl/maps?q=80beans,<%= @meetup.venue.address_1 %>,<%= @meetup.venue.city %>&amp;hl=nl&amp;sll=<%= @meetup.venue.lat %>,<%= @meetup.venue.lon %>&amp;sspn=3.87879,3.779297&amp;hq=80beans,&amp;hnear=Vijzelstraat+72,+Amsterdam,+Noord-Holland&amp;t=m&amp;z=17"><img src="http://maps.googleapis.com/maps/api/staticmap?center=<%= @meetup.venue.lat %>,<%= @meetup.venue.lon %>&amp;zoom=14&amp;size=940x505&amp;sensor=false&amp;markers=color:blue|<%= @meetup.venue.address_1 %>, <%= @meetup.venue.city %>" alt="map" /></a></div>
  </div>
</section>

app/views/meetups/edit.html.erb
<h1>Editing meetup</h1>

<%= render 'form' %>

<%= link_to 'Show', @meetup %> |
<%= link_to 'Back', meetups_path %>

app/views/meetups/index.html.erb
<%= render 'meetup' %>

<% unless user_signed_in? %>
<strong>Authentication:</strong>
<ul>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
</ul>
<% else %>
You are signed in as <%= link_to current_user.email, 'mailto:current_user.email' %>
<br>
<%= link_to 'Sign out', destroy_user_session_path, method: 'delete' %>
<% end %>

app/views/meetups/new.html.erb
<h1>New meetup</h1>

<%= render 'form' %>

<%= link_to 'Back', meetups_path %>

app/views/meetups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @meetup.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @meetup.date %>
</p>

<p>
  <strong>Address:</strong>
  <%= @meetup.address %>
</p>

<p>
  <strong>Host:</strong>
  <%= @meetup.host_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @meetup.description %>
</p>

<p>
  <strong>Meetup url:</strong>
  <%= @meetup.meetup_url %>
</p>

<%= link_to 'Edit', edit_meetup_path(@meetup) %> |
<%= link_to 'Back', meetups_path %>

app/views/shared/_footer.html.erb
<footer id="footer" class="wrap">
    <ul id="socnet">
      <li><a class="twitter" href="http://twitter.com/amsrb">twitter</a></li>
      <li><a class="github" href="https://github.com/amsrb">github</a></li>
    </ul>
  <p>Contact us: <a href="mailto:contact@amsrb.org">contact@amsrb.org</a>.</p>
</footer>

app/views/shared/_header.html.erb
<header id="header">
  <div class="wrap">
    <h1 id="logo"><a href="/"><%= image_tag 'logo.png', alt: 'Amsterdam.rb'%></a></h1>
    <p id="intro">We aim at promoting all the aspects of the Ruby programming language and at fostering a vivid Ruby community in the Amsterdam region.</p>
  </div>
   <nav>
    <ul>
        <li>
            <a href="/">HOME</a> |
            <%= link_to 'JOBS', jobs_path %> |
        </li>
     </ul>
</nav>
</header>

app/views/shared/_supporters.html.erb
<section id="supporters">
      <h1 class="tag">
        <span class="tagleft"></span>
        <span class="text">
          <span><span>Our Awesome </span>Supporters</span>
        </span>
        <span class="tagright"></span>
      </h1>
      <ul>
        <li>
          <a href="http://appsignal.com/"><div class="image_box">
            <%= image_tag 'logo/appsignal.png', alt: '80beans' %>
          </div>
          </a>
        </li>
        <li>
          <a href="http://www.80beans.com/"><div class="image_box">
            <%= image_tag 'logo/80beans.png', alt: '80beans' %>
          </div>
          </a>
        </li>
        <li>
          <a href="http://www.publitas.com/"><div class="image_box">
            <%= image_tag 'logo/publitas.png', alt: 'Publitas' %>
          </div>
          </a>
        </li>
        <li>
          <a href="http://www.true.nl/"><div class="image_box">
            <%= image_tag 'logo/true.png', alt: 'TRUE' %>
          </div></a>
        </li>
        <li>
          <a href="http://www.zilverline.com/"><div class="image_box">
            <%= image_tag 'logo/zilverline.png', alt: 'Zilverline' %>
          </div></a>
        </li>
        <li>
          <a href="http://www.github.com/"><div class="image_box">
            <%= image_tag 'logo/github.png', alt: 'GitHub' %>
          </div></a>
        </li>
        <li>
          <a href="http://www.innovationfactory.eu/"><div class="image_box">
            <%= image_tag 'logo/if.png', alt: 'Innovation Factory' %>
          </div></a>
        </li>
        <li>
          <a href="http://www.springest.nl/"><div class="image_box">
            <%= image_tag 'logo/springest.png', alt: 'Springest' %>
          </div></a>
        </li>
      </ul>
    </section>